version: "3.8"
services:
  dnsdocker:
    image: moralitos28/dnsmasq:latest
    network_mode: host
    container_name: dnsmasq
    restart: on-failure
    volumes: #Modify personal directory were .conf were located
        - ./config:/etc/dnsmasq.d
